version: 40
imports:
- projectPath: OpenMandriva/Software
  revision: mirroring
jobs:
- name: Build minimal image (Docker)
  jobExecutor: docker-with-mount-cap
  steps:
  - !UseTemplateStep
    name: Build
    templateName: Build
    paramMatrix:
    - name: version
      secret: false
      valuesProvider: !PassthroughValues
        paramName: version
    - name: target
      secret: false
      valuesProvider: !ScriptingValues
        scriptName: docker-arch-to-omv-build-target
    - name: extra-args
      secret: false
      valuesProvider: !SpecifiedValues
        values:
        - - -P rootfs -W @param:extra-args@
    condition: SUCCESSFUL
    optional: false
  - !UseTemplateStep
    name: Push to registry
    templateName: Push image (Docker)
    paramMatrix:
    - name: docker-arch
      secret: false
      valuesProvider: !PassthroughValues
        paramName: docker-arch
    - name: dockerfile-path
      secret: false
      valuesProvider: !SpecifiedValues
        values:
        - - helpers/Dockerfile
    - name: image-url
      secret: false
      valuesProvider: !SpecifiedValues
        values:
        - - openmandriva/minimal:@param:version@
    condition: SUCCESSFUL
    optional: false
  paramSpecs:
  - !ChoiceParam
    name: version
    allowMultiple: false
    allowEmpty: false
    choiceProvider: !SpecifiedChoices
      choices:
      - value: cooker
        color: '#0d87e9'
      - value: rolling
        color: '#0d87e9'
      - value: rock
        color: '#0d87e9'
    defaultValueProvider: !SpecifiedDefaultValue
      value: cooker
  - !ChoiceParam
    name: docker-arch
    allowMultiple: false
    allowEmpty: false
    choiceProvider: !SpecifiedChoices
      choices:
      - value: amd64
        color: '#0d87e9'
      - value: arm64
        color: '#0d87e9'
  - !TextParam
    name: extra-args
    allowEmpty: true
    multiline: false
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400
- name: Build builder image (Docker)
  jobExecutor: docker-with-mount-cap
  steps:
  - !UseTemplateStep
    name: Checkout repository
    templateName: Checkout
    condition: SUCCESSFUL
    optional: false
  - !UseTemplateStep
    name: Push to registry
    templateName: Push image (Docker)
    paramMatrix:
    - name: docker-arch
      secret: false
      valuesProvider: !PassthroughValues
        paramName: docker-arch
    - name: dockerfile-path
      secret: false
      valuesProvider: !SpecifiedValues
        values:
        - - helpers/Dockerfile_builder
    - name: image-url
      secret: false
      valuesProvider: !SpecifiedValues
        values:
        - - openmandriva/builder:latest
    condition: SUCCESSFUL
    optional: false
  paramSpecs:
  - !ChoiceParam
    name: docker-arch
    allowMultiple: false
    allowEmpty: false
    choiceProvider: !SpecifiedChoices
      choices:
      - value: amd64
        color: '#0d87e9'
      - value: arm64
        color: '#0d87e9'
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400
stepTemplates:
- name: Checkout
  steps:
  - !CheckoutStep
    name: Checkout repository
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    cloneDepth: 1
    condition: SUCCESSFUL
    optional: false
- name: Build
  steps:
  - !UseTemplateStep
    name: Checkout repository
    templateName: Checkout
    condition: SUCCESSFUL
    optional: false
  - !CommandStep
    name: Run build script in container
    runInContainer: true
    image: openmandriva/minimal:cooker
    interpreter: !DefaultInterpreter
      commands: "set -ex\n\necho insecure >> ~/.curlrc\n\ndnf --assumeyes --no-docs --setopt=install_weak_deps=False --refresh upgrade\ndnf --assumeyes --no-docs --setopt=install_weak_deps=False install timezone systemd git\n\n./build @param:extra-args@ -v @param:version@ @param:target@\n\nfolder=$(find . -maxdepth 1 -type d -name \"OpenMandriva-Lx-*\")\nif [ -n \"$folder\" ]; then\n\tmv \"$folder\" \"output\"\nfi\n"
    useTTY: true
    condition: SUCCESSFUL
    optional: false
  paramSpecs:
  - !TextParam
    name: version
    allowEmpty: false
    multiline: false
  - !TextParam
    name: target
    allowEmpty: false
    multiline: false
  - !TextParam
    name: extra-args
    allowEmpty: true
    multiline: false
- name: Push image (Docker)
  steps:
  - !CommandStep
    name: Push to registry
    runInContainer: true
    image: quay.io/podman/stable
    interpreter: !DefaultInterpreter
      commands: |
        set -e

        dnf install --assumeyes skopeo

        current_arch=@param:docker-arch@
        image_url="@param:image-url@"

        mkdir -p output

        echo "🛠 Building image: $image_url_arch"
        podman build \
          --arch $current_arch \
          --os linux \
          -f "@param:dockerfile-path@" \
          -t "$image_url.$current_arch" \
          output

        # Local registry
        registry_url="@server@/$image_url"
        echo "📤 Pushing image to: $registry_url.$current_arch"
        podman login "@server@" -u "@job_token@" -p "@secret:local_registry_token@"
        podman push "$image_url.$current_arch" "$registry_url.$current_arch"

        manifest_args=""
        architectures=("arm64" "amd64")

        echo "🛠 Creating manifest for: $image_url"
        podman manifest create "$image_url"

        for arch in "${architectures[@@]}"; do
          image="docker://$registry_url.$arch"
          echo "🔍 Inspecting image at: $image"

          if skopeo inspect "$image" &>/dev/null; then
            echo "✅ Image found for: $arch"
            podman manifest add \
              --arch $arch \
              --os linux \
              "$image_url" \
              "$image"
          else
            echo "⚠️ Image not found for: $arch"
          fi
        done

        echo "📤 Pushing manifest to: $registry_url"
        podman push "$image_url" "$registry_url"

        # Remote registry
        registry_url="@property:remote_registry@/$image_url"
        echo "📤 Pushing image to: $registry_url.$current_arch"
        podman login "@property:remote_registry@" -u "@secret:remote_registry_user@" -p "@secret:remote_registry_token@"
        podman push "$image_url.$current_arch" "$registry_url.$current_arch"

        echo "📤 Pushing manifest to: $registry_url"
        podman push "$image_url" "$registry_url"
    useTTY: true
    condition: SUCCESSFUL
    optional: false
  paramSpecs:
  - !TextParam
    name: docker-arch
    allowEmpty: false
    multiline: false
  - !TextParam
    name: dockerfile-path
    allowEmpty: false
    multiline: false
  - !TextParam
    name: image-url
    allowEmpty: false
    multiline: false
