version: 40
imports:
- projectPath: OpenMandriva/Software
  revision: mirroring
jobs:
- name: Publish Docker image
  jobExecutor: docker-with-mount-cap
  steps:
  - !UseTemplateStep
    name: Build
    templateName: Build
    paramMatrix:
    - name: version
      secret: false
      valuesProvider: !PassthroughValues
        paramName: version
    - name: target
      secret: false
      valuesProvider: !ScriptingValues
        scriptName: docker-arch-to-omv-build-target
    - name: extra-args
      secret: false
      valuesProvider: !SpecifiedValues
        values:
        - - -P core @param:extra-args@
    condition: SUCCESSFUL
    optional: false
  - !CommandStep
    name: Push Docker image
    runInContainer: true
    image: quay.io/podman/stable
    interpreter: !DefaultInterpreter
      commands: "set -e\n\ncurrent_arch=@param:docker-arch@\n\nimage_tag=\"@param:version@\"\nimage_name=\"@property:registry_repo@/minimal\"\nimage_url=\"@server@/$image_name:$image_tag\"\n\npodman login \"@server@\" -u \"@job_token@\" -p \"@secret:registry_token@\"\n\necho \"🛠📤 Building and pushing image: $image_url.$current_arch\"\npodman build \\\n  --arch $current_arch \\\n  --os linux \\\n  -f helpers/Dockerfile \\\n  -t \"$image_url.$current_arch\" \\\n  output\npodman push \"$image_url.$current_arch\"\n\nmanifest_args=\"\"\narchitectures=(\"arm64\" \"amd64\")\n\necho \"🛠 Creating manifest: $image_name:$image_tag\"\npodman manifest create \"$image_name:$image_tag\"\n\nfor arch in \"${architectures[@@]}\"; do\n  image=\"docker://$image_url.$arch\"\n  echo \"🔍 Inspecting manifest for: $image\"\n\n  if podman image inspect \"$image\" &>/dev/null; then\n    echo \"✅ Image found for $arch\"\n    podman manifest add\n\t  --arch $arch \\\n\t  --os linux \\\n\t  \"$image_name:$image_tag\" \\\n\t  \"$image\"\n  else\n    echo \"⚠️ No image found for $arch\"\n  fi\ndone\n\necho \"📤 Pushing manifest: $image_base\"\npodman push \"$image_name:$image_tag\" \"docker://$image_url\"\n"
    useTTY: true
    condition: SUCCESSFUL
    optional: false
  paramSpecs:
  - !ChoiceParam
    name: version
    allowMultiple: false
    allowEmpty: false
    choiceProvider: !SpecifiedChoices
      choices:
      - value: cooker
        color: '#0d87e9'
      - value: rolling
        color: '#0d87e9'
      - value: rock
        color: '#0d87e9'
    defaultValueProvider: !SpecifiedDefaultValue
      value: cooker
  - !ChoiceParam
    name: docker-arch
    allowMultiple: false
    allowEmpty: false
    choiceProvider: !SpecifiedChoices
      choices:
      - value: amd64
        color: '#0d87e9'
      - value: arm64
        color: '#0d87e9'
  - !TextParam
    name: extra-args
    allowEmpty: true
    multiline: false
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400
stepTemplates:
- name: Build
  steps:
  - !CheckoutStep
    name: Checkout repository
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    cloneDepth: 1
    condition: SUCCESSFUL
    optional: false
  - !CommandStep
    name: Run build script in container
    runInContainer: true
    image: openmandriva/cooker
    interpreter: !DefaultInterpreter
      commands: "set -ex\n\necho insecure >> ~/.curlrc\n\ndnf --assumeyes --no-docs --setopt=install_weak_deps=False --refresh upgrade\ndnf --assumeyes --no-docs --setopt=install_weak_deps=False install timezone systemd git\n\n./build @param:extra-args@ -v @param:version@ @param:target@\n\nfolder=$(find . -maxdepth 1 -type d -name \"OpenMandriva-Lx-*\")\nif [ -n \"$folder\" ]; then\n\tmv \"$folder\" \"output\"\nfi\n"
    useTTY: true
    condition: SUCCESSFUL
    optional: false
  paramSpecs:
  - !TextParam
    name: version
    allowEmpty: false
    multiline: false
  - !TextParam
    name: target
    allowEmpty: false
    multiline: false
  - !TextParam
    name: extra-args
    allowEmpty: true
    multiline: false
