version: 40
imports:
- projectPath: OpenMandriva/Software
  revision: mirroring
jobs:
- name: Build Docker image
  steps:
  - !UseTemplateStep
    name: Build minimal Docker image
    templateName: Build Docker image
    paramMatrix:
    - name: version
      secret: false
      valuesProvider: !SpecifiedValues
        values:
        - - cooker
    - name: architecture
      secret: false
      valuesProvider: !SpecifiedValues
        values:
        - - aarch64
    - name: extra-parameters
      secret: false
      valuesProvider: !SpecifiedValues
        values:
        - - -P core
    condition: SUCCESSFUL
    optional: false
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400
stepTemplates:
- name: Build
  steps:
  - !CheckoutStep
    name: Checkout repository
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    cloneDepth: 1
    condition: SUCCESSFUL
    optional: false
  - !CommandStep
    name: Run build script in container
    runInContainer: true
    image: openmandriva/cooker
    interpreter: !DefaultInterpreter
      commands: |
        dnf --assumeyes --no-docs --setopt=install_weak_deps=False --refresh upgrade
        dnf --assumeyes --no-docs --setopt=install_weak_deps=False install timezone systemd git

        ./build @param:extra-parameters@ -v @param:version@ @param:target@
    useTTY: true
    condition: SUCCESSFUL
    optional: false
  paramSpecs:
  - !TextParam
    name: version
    allowEmpty: false
    multiline: false
  - !TextParam
    name: target
    allowEmpty: false
    multiline: false
  - !TextParam
    name: extra-parameters
    allowEmpty: true
    multiline: false
- name: Build Docker image
  steps:
  - !UseTemplateStep
    name: Build
    templateName: Build
    paramMatrix:
    - name: version
      secret: false
      valuesProvider: !PassthroughValues
        paramName: version
    - name: target
      secret: false
      valuesProvider: !SpecifiedValues
        values:
        - - '@param:architecture@-rootfs'
    - name: extra-parameters
      secret: false
      valuesProvider: !SpecifiedValues
        values:
        - - '@param:extra-parameters@'
    condition: SUCCESSFUL
    optional: false
  - !CommandStep
    name: Test
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands: |
        echo "test"
    useTTY: true
    condition: SUCCESSFUL
    optional: false
  paramSpecs:
  - !TextParam
    name: version
    allowEmpty: false
    multiline: false
  - !ChoiceParam
    name: architecture
    allowMultiple: false
    allowEmpty: false
    choiceProvider: !SpecifiedChoices
      choices:
      - value: aarch64
        color: '#0d87e9'
      - value: x86-64
        color: '#0d87e9'
      - value: znver1
        color: '#0d87e9'
  - !TextParam
    name: extra-parameters
    allowEmpty: false
    multiline: false
